services:
  webapp:
    build: ./go
    environment:
      ISUCON_DB_HOST1: 10.0.0.182
      ISUCON_DB_HOST2: 10.0.0.137
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
      PPROF: 1
    network_mode: host
    volumes:
      - /home/isucon/isucon12-qualify/webapp/tenant_db:/home/isucon/isucon12-qualify/webapp/tenant_db
      - /home/isucon/isucon12-qualify/webapp/sql:/home/isucon/isucon12-qualify/webapp/sql
      - /home/isucon/isucon12-qualify/webapp/public.pem:/home/isucon/isucon12-qualify/webapp/public.pem:ro
      - /home/isucon/isucon12-qualify/initial_data:/home/isucon/isucon12-qualify/initial_data
      - /home/isucon/isucon12-qualify/tmp:/home/isucon/isucon12-qualify/tmp
    init: true
    ports:
      - "127.0.0.1:1080:1080"